name: Build

on:
  workflow_call:
    inputs:
      jdk:
        type: number
        default: 11
      goals:
        type: string
        default: 'clean package'
    secrets:
      PACKAGES_TOKEN:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.jdk }}
    - name: Configure Maven
      run: |
        mkdir -p ~/.m2
        echo "<settings>
                <servers>
                  <server><id>github</id><username>x-access-token</username><password>${{ secrets.GITHUB_TOKEN }}</password></server>
                  <server><id>github-origin-legacy</id><username>x-access-token</username><password>${{ secrets.PACKAGES_TOKEN }}</password></server>
                  <server><id>github-origin-gt-legacy</id><username>x-access-token</username><password>${{ secrets.PACKAGES_TOKEN }}</password></server>
                  <server><id>github-hrfi-v2</id><username>x-access-token</username><password>${{ secrets.PACKAGES_TOKEN }}</password></server>
                  <server><id>github-hrfi-ecvo</id><username>x-access-token</username><password>${{ secrets.PACKAGES_TOKEN }}</password></server>
                  <server><id>github-hrfi-okonomi</id><username>x-access-token</username><password>${{ secrets.PACKAGES_TOKEN }}</password></server>
                </servers>
              </settings>" > ~/.m2/settings.xml
    - name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B ${{ inputs.goals }} --file pom.xml
